---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nexus-iq-server
  namespace: sonatype
spec:
  port:
    targetPort: 8070
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nexus-iq-server-iqserver
    weight: 100
